// <auto-generated />
using AKOK_BlazorServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AKOK_BlazorServer.Data.FortuneMigration
{
    [DbContext(typeof(FortuneDbContext))]
    [Migration("20230409032219_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("AKOK_BlazorServer.Models.ResultText", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongText")
                        .HasColumnType("TEXT");

                    b.HasKey("Number");

                    b.ToTable("ResultTexts");
                });
#pragma warning restore 612, 618
        }
    }
}
